language: bash
sudo: required
env:
- DISTRO=ubuntu-trusty

before_script:
    - sudo ls -l /sys/class/net
    - sudo ls -l --dereference /sys/class/net 
    - sudo ls -lad /sys/class
    - sudo ls -lad /sys/devices
    - sudo chmod a+x /sys
    - sudo chmod a+rx /sys/class
    - sudo chmod a+r /sys/class/net
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tmux
    - mailutils
    - postfix 
    - lib32gcc1 
    - libstdc++6 
    - libstdc++6:i386 
    - telnet 
    - expect

script:

    - bash tests/tests_jc2server.sh
    - bash tests/tests_ts3server.sh
